# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 07:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 22, 15, 40, 45, 785695))),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 22, 15, 40, 45, 785125))),
                ('url', models.CharField(max_length=500)),
            ],
        ),
    ]
