# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0002_auto_20170722_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='videos',
            name='created_time',
            field=models.DateTimeField(),
        ),
    ]
