# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 03:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0004_auto_20170722_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board_Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Latest_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='News',
            new_name='Board_News',
        ),
    ]
