# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0005_auto_20170723_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board_news',
            name='body',
        ),
        migrations.RemoveField(
            model_name='latest_news',
            name='body',
        ),
        migrations.AddField(
            model_name='board_news',
            name='img_src',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='board_videos',
            name='img_src',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='latest_news',
            name='img_src',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='videos',
            name='img_src',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
