# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0006_auto_20170723_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_news',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='latest_news',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='board_videos',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='videos',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
