# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 17:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0008_lx_lx_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='lx',
            name='created_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
