# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 05:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0011_hoop_latest_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hoop_Hot_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
