# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0012_hoop_hot_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latest_news',
            name='img_src',
        ),
    ]
