# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 11:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0013_remove_latest_news_img_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('game_tag', models.CharField(blank=True, max_length=200)),
                ('game_time', models.CharField(blank=True, max_length=200)),
                ('first_team_logo', models.CharField(blank=True, max_length=200)),
                ('first_team_name', models.CharField(blank=True, max_length=200)),
                ('second_team_name', models.CharField(blank=True, max_length=200)),
                ('second_team_logo', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
