# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 22:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0014_jrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZiMeiTi_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.CharField(blank=True, max_length=200)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
                ('video_url', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
