# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0015_zimeiti_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZiMeiTi_Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='zimeiti_article',
            name='url',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='zimeiti_img',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainAPP.ZiMeiTi_Article'),
        ),
    ]
